
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://yistohnedvvneryjxrwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpc3RvaG5lZHZ2bmVyeWp4cndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDE2MjEsImV4cCI6MjA2MjI3NzYyMX0.DVfAT9zmnqY1O-o28E1VRQT4iTmRwmgclA-pc2GcQKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
